### ISSUE TITLE
Support per-behavior axes

### ISSUE THREAD

**Issue by kriskowal** [yarpc/crossdock#39]
Docker compose environment would look like:

``` yaml
services:
    crossdock:
        environment:
            - CROSSDOCK_WAIT_FOR=yarpc-node,yarpc-go,yarpc-python,yarpc-java

            - CROSSDOCK_AXIS_CLIENT=yarpc-node,yarpc-go,yarpc-python,yarpc-java
            - CROSSDOCK_AXIS_SERVER=yarpc-node,yarpc-go,yarpc-python,yarpc-java
            - CROSSDOCK_AXIS_BAD_HOST=yarpc-node

            - CROSSDOCK_BEHAVIOR_ECHO=client,server,transport
            - CROSSDOCK_BEHAVIOR_RAW=client,server
            - CROSSDOCK_BEHAVIOR_JSON=client,server
            - CROSSDOCK_BEHAVIOR_THRIFT=client,server
            - CROSSDOCK_BEHAVIOR_BAD_INBOUND=bad-host,server
            - CROSSDOCK_BEHAVIOR_BAD_OUTBOUND=client,bad-host
```

Note that this separates WAIT_FOR and CLIENT into semantically separate headers (with the same value). The BEHAVIORS header disappears and is implied by the enumeration of behavior environment variables.
