### ISSUE TITLE
Remove CROSSDOCK_ prefix on configuration

### ISSUE THREAD

**Issue by HelloGrayson** [yarpc/crossdock#45]
I've been tossing and turning on this one. While the prefix is a best practice, removing it saves big time on config character counts, which really really helps readability and usability:

```
version: '2'

services:
    crossdock:
        image: yarpc/crossdock
        links:
            - python
            - python-sync
            - go
            - java
            - node
        environment:
            - WAIT_FOR=python,python-sync,node,go,java

            - AXIS_CLIENT=python,python-sync,node,go,java
            - AXIS_SERVER=python,node,go,java
            - AXIS_TRANSPORT=http,tchannel

            - BEHAVIOR_RAW=client,server,transport
            - BEHAVIOR_JSON=client,server,transport
            - BEHAVIOR_THRIFT=client,server,transport
```

I'm leaning towards that this is worth it, despite ignoring the best practice. What do you guys think?
