### ISSUE TITLE
Support yaml

### ISSUE THREAD

**Issue by HelloGrayson** [yarpc/crossdock#50]
environment vars are getting a bit tricky to support - especially for advanced usage like #49 

Perhaps we can do something like:

```
version: '2'

services:
    crossdock:
        image: yarpc/crossdock
        volumes:
            - .:/usr/src/crossdock
```

Where we look for a `crossdock.yaml` in `/usr/src/crossdock` (path up for debate), and if its not there, use env vars.
